// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdP08hg3DVNIKmDsak87hmhOZ3EI6WQeQ',
    appId: '1:279325464526:web:c1b2ac070986e5f883fd9f',
    messagingSenderId: '279325464526',
    projectId: 'smarttasks-3eb46',
    authDomain: 'smarttasks-3eb46.firebaseapp.com',
    storageBucket: 'smarttasks-3eb46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9baYN5VpxeNCeYODK3kfaTGl_HA0H580',
    appId: '1:279325464526:android:63bc56e9f4295fed83fd9f',
    messagingSenderId: '279325464526',
    projectId: 'smarttasks-3eb46',
    storageBucket: 'smarttasks-3eb46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaIyL62BnsQdwWCz-WlVZO8C2VacsU3A',
    appId: '1:279325464526:ios:bce79abbb2664abe83fd9f',
    messagingSenderId: '279325464526',
    projectId: 'smarttasks-3eb46',
    storageBucket: 'smarttasks-3eb46.firebasestorage.app',
    androidClientId: '279325464526-30a1rq4g96omfo7gsjk26ervfu418ph3.apps.googleusercontent.com',
    iosClientId: '279325464526-o84lp7qa6a6i0k9j8bnu3ega00aece44.apps.googleusercontent.com',
    iosBundleId: 'com.example.sourcecodeBai3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtaIyL62BnsQdwWCz-WlVZO8C2VacsU3A',
    appId: '1:279325464526:ios:bce79abbb2664abe83fd9f',
    messagingSenderId: '279325464526',
    projectId: 'smarttasks-3eb46',
    storageBucket: 'smarttasks-3eb46.firebasestorage.app',
    androidClientId: '279325464526-30a1rq4g96omfo7gsjk26ervfu418ph3.apps.googleusercontent.com',
    iosClientId: '279325464526-o84lp7qa6a6i0k9j8bnu3ega00aece44.apps.googleusercontent.com',
    iosBundleId: 'com.example.sourcecodeBai3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdP08hg3DVNIKmDsak87hmhOZ3EI6WQeQ',
    appId: '1:279325464526:web:555f8d632acd21c883fd9f',
    messagingSenderId: '279325464526',
    projectId: 'smarttasks-3eb46',
    authDomain: 'smarttasks-3eb46.firebaseapp.com',
    storageBucket: 'smarttasks-3eb46.firebasestorage.app',
  );

}